
import { AppData } from './types';

// Removed GIFS constant object as direct linking is unreliable

export const PLAYER_CODE_MAP: Record<string, { firstName: string; lastName: string }> = {
  'GORA8392': { firstName: 'RUBEN', lastName: 'APARICIO' },
  'GORD1047': { firstName: 'RUSU', lastName: 'DENIS' },
  'GOLA3819': { firstName: 'LORIEN', lastName: 'ARNAL' },
  'GOMT9254': { firstName: 'MOHAMMED', lastName: 'TAGHILTI' },
  'GOJQ6118': { firstName: 'JORGE', lastName: 'QUATRONNE P' },
  'GOLA2845': { firstName: 'LUCAS', lastName: 'AROYO' },
  'GOPB7402': { firstName: 'PABLO', lastName: 'BERDEJO' },
  'GOJC5936': { firstName: 'JESUS', lastName: 'CLAVERIA' },
  'GODF1773': { firstName: 'DARIO', lastName: 'FELIPE' },
  'GOJC8460': { firstName: 'JAVIER', lastName: 'COLELL' },
  'GOPG4921': { firstName: 'PABLO', lastName: 'GARCIA' },
  'GONG3305': { firstName: 'NICOLAS', lastName: 'GARCIA' },
  'GOHP9588': { firstName: 'HUGO', lastName: 'PRADOS' },
  'GODG6241': { firstName: 'DIEGO', lastName: 'GELABERT' },
  'GOPL1897': { firstName: 'PEDRO', lastName: 'LATORRE' },
  'GOBG7533': { firstName: 'BRUNO', lastName: 'GOMEZ' },
  'GOJM5519': { firstName: 'JORGE', lastName: 'MARTIN' },
  'GOMJ2964': { firstName: 'MARIO', lastName: 'JOSE' },
  'GOAC4170': { firstName: 'ALEX', lastName: 'COWASZ' },
  'GOSA6733': { firstName: 'SALIU', lastName: 'SALIU' }, // Assuming Saliu Saliu based on single name
  'GOTI9201': { firstName: 'TEODOR', lastName: 'IVANOV' },
  'GODE4857': { firstName: 'DANIEL', lastName: 'ESPEJO' },
  'GOHL1123': { firstName: 'HUGO', lastName: 'LOBERA P' },
  'GODM7698': { firstName: 'DANIEL', lastName: 'MURCIA' },
  'GOKI3448': { firstName: 'KILIAN', lastName: 'KILIAN' }, // Assuming Kilian Kilian
  'GOJU8025': { firstName: 'JULEN', lastName: 'JULEN' },   // Assuming Julen Julen
  'GOMO5381': { firstName: 'MOHA', lastName: 'MOHA' },     // Assuming Moha Moha
  'GOCR9874': { firstName: 'CRISTIAN', lastName: 'CRISTIAN' }, // Assuming Cristian Cristian
  'GOEN6509': { firstName: 'ERIC', lastName: 'NAVARRO' },
  'GOUR2216': { firstName: 'URIEL', lastName: 'REYES' },
  'GOGS8842': { firstName: 'GEORGE', lastName: 'STOICA' },
  'GOPL3177': { firstName: 'PABLO', lastName: 'LACOMA' },
  'GOJM9403': { firstName: 'JAVI', lastName: 'MIRAMON' },
  'GOVP6650': { firstName: 'VICTOR', lastName: 'PARDOS' },
  'GOLG2086': { firstName: 'LUCAS', lastName: 'GAUDES' },
  'GOME5714': { firstName: 'MARCOS', lastName: 'EZQUERRA' },
  'GOMI1390': { firstName: 'MIGUEL', lastName: 'MIGUEL' }, // Assuming Miguel Miguel
  'GOAT7829': { firstName: 'ALI', lastName: 'TAYYAB' },
  'GODC4551': { firstName: 'DAVID', lastName: 'CIOCAN' },
  'GORD8138': { firstName: 'RAUL', lastName: 'DOMITRASCU' },
  'GORF2815': { firstName: 'ROBERTO', lastName: 'FERNANDO' },
  'GOEF5472': { firstName: 'ENRIQUE', lastName: 'FLORIA' },
  'GOMT1907': { firstName: 'MIGUEL', lastName: 'TORNERO' },
  'GODM6394': { firstName: 'DIEGO', lastName: 'MARTINEZ' },
  'GOHN9720': { firstName: 'HUGO', lastName: 'NAVARRO' },
  'GODN3056': { firstName: 'DARIO', lastName: 'NOGUERAS' },
  'GOAD8612': { firstName: 'ALAN', lastName: 'DAYAN' },
  'GORM4383': { firstName: 'RAUL', lastName: 'MAG' },
  'GOLB7019': { firstName: 'LOKMAN', lastName: 'BENCHOHRA' },
  'GORV2645': { firstName: 'RAUL', lastName: 'VILLASANTE' },
  'GOAC5181': { firstName: 'AIMAR', lastName: 'CALVO' },
  'GOSD9937': { firstName: 'SEBASTIAN', lastName: 'DELGADO' },
  'GOBR1564': { firstName: 'BRAHIM', lastName: 'BRAHIM' }, // Assuming Brahim Brahim
  'GORG4790': { firstName: 'RENAN', lastName: 'GIRELLI' },
  'GOYL8228': { firstName: 'YAGO', lastName: 'LORENTE' },
  'GOJM7304': { firstName: 'JOSE MANUEL', lastName: 'MERINO' },
  'GOMS4829': { firstName: 'MATEO', lastName: 'SANTABARBARA' },
  'GORM3364': { firstName: 'RODRIGO', lastName: 'MUÑOZ' }
};


export const TRAINING_DATA: AppData = {
  programName: "Rutina de entrenamiento – Julio y primera semana de agosto",
  trainerName: "SERGIO GIL",
  objective: "Mantener la forma física, mejorar velocidad, resistencia, fuerza y flexibilidad sin sobrecarga. Se incorporan ejercicios técnicos con balón en las últimas semanas.",
  postWorkoutStretch: {
    label: "ESTIRAMIENTO POSTENTRENO",
    url: "https://youtu.be/h6tQ0kGHt2M"
  },
  weeks: [
    {
      weekNumber: 1,
      title: "Semana 1 (Adaptación – 3 días de entrenamiento)",
      days: [
        {
          dayName: "Día 1",
          exercises: [
            { name: "Carrera suave", repetitions: "10 min", rest: "3 min" },
            { name: "Saltos a la comba", repetitions: "2:30 min", rest: "30 seg" },
            { name: "Saltos a la comba", repetitions: "2:30 min", rest: "30 seg" },
            { name: "Sprint 20 m", repetitions: "1", rest: "30 seg" },
            { name: "Flexiones", repetitions: "10", rest: "30 seg" },
            { name: "Sentadillas", repetitions: "15", rest: "30 seg" },
            { name: "Sprint 20 m", repetitions: "1", rest: "30 seg" },
            { name: "Flexiones", repetitions: "10", rest: "30 seg" },
            { name: "Sentadillas", repetitions: "15", rest: "30 seg" },
            { name: "Sprint 20 m", repetitions: "1", rest: "30 seg" },
            { name: "Flexiones", repetitions: "10", rest: "30 seg" },
            { name: "Sentadillas", repetitions: "15", rest: "30 seg" },
            { name: "Sprint 20 m", repetitions: "1", rest: "30 seg" },
            { name: "Estiramientos", repetitions: "10 min", rest: "-" },
          ],
        },
        {
          dayName: "Día 2",
          notes: "Actividad libre (Ciclismo, escalada, senderismo, tenis, pádel, baloncesto, natación, etc.)",
          exercises: [],
        },
        {
          dayName: "Día 3",
          exercises: [
            { name: "Carrera continua", repetitions: "15 min", rest: "5 min" },
            { name: "Skipping alto", repetitions: "30 seg", rest: "30 seg" },
            { name: "Zancadas", repetitions: "12", rest: "30 seg" },
            { name: "Burpees", repetitions: "10", rest: "30 seg" },
            { name: "Skipping alto", repetitions: "30 seg", rest: "30 seg" },
            { name: "Zancadas", repetitions: "12", rest: "30 seg" },
            { name: "Burpees", repetitions: "10", rest: "30 seg" },
            { name: "Skipping alto", repetitions: "30 seg", rest: "30 seg" },
            { name: "Zancadas", repetitions: "12", rest: "30 seg" },
            { name: "Burpees", repetitions: "10", rest: "30 seg" },
            { name: "Skipping alto", repetitions: "30 seg", rest: "30 seg" },
            { name: "Estiramientos", repetitions: "10 min", rest: "-" },
          ],
        },
      ],
    },
    {
      weekNumber: 2,
      title: "Semana 2 (4 días de entrenamiento)",
      days: [
        {
          dayName: "Día 1",
          exercises: [
            { name: "Saltos a la comba", repetitions: "2:30 min", rest: "30 seg" },
            { name: "Saltos a la comba", repetitions: "2:30 min", rest: "30 seg" },
            { name: "Sprint 30 m", repetitions: "2", rest: "30 seg" },
            { name: "Flexiones", repetitions: "12", rest: "30 seg" },
            { name: "Sentadillas", repetitions: "15", rest: "30 seg" },
            { name: "Abdominales pies suelo", repetitions: "15", rest: "30 seg" },
            { name: "Sprint 30 m", repetitions: "2", rest: "30 seg" },
            { name: "Flexiones", repetitions: "12", rest: "30 seg" },
            { name: "Sentadillas", repetitions: "15", rest: "30 seg" },
            { name: "Abdominales pies suelo", repetitions: "15", rest: "30 seg" },
            { name: "Sprint 30 m", repetitions: "2", rest: "30 seg" },
            { name: "Flexiones", repetitions: "12", rest: "30 seg" },
            { name: "Sentadillas", repetitions: "15", rest: "30 seg" },
            { name: "Abdominales pies suelo", repetitions: "10", rest: "30 seg" },
            { name: "Sprint 30 m", repetitions: "2", rest: "30 seg" },
            { name: "Estiramientos", repetitions: "10 min", rest: "-" },
          ],
        },
        {
          dayName: "Día 2",
          notes: "Actividad libre (Ciclismo, escalada, senderismo, tenis, pádel, baloncesto, natación, etc.)",
          exercises: [],
        },
        {
          dayName: "Día 3",
          exercises: [
            { name: "Carrera continua", repetitions: "20 min", rest: "5 min" },
            { name: "Skipping alto", repetitions: "30 seg", rest: "30 seg" },
            { name: "Zancadas", repetitions: "12", rest: "30 seg" },
            { name: "Burpees", repetitions: "10", rest: "30 seg" },
            { name: "Skipping alto", repetitions: "30 seg", rest: "30 seg" },
            { name: "Zancadas", repetitions: "12", rest: "30 seg" },
            { name: "Burpees", repetitions: "10", rest: "30 seg" },
            { name: "Skipping alto", repetitions: "30 seg", rest: "30 seg" },
            { name: "Zancadas", repetitions: "12", rest: "30 seg" },
            { name: "Burpees", repetitions: "10", rest: "30 seg" },
            { name: "Skipping alto", repetitions: "30 seg", rest: "30 seg" },
            { name: "Estiramientos", repetitions: "10 min", rest: "-" },
          ],
        },
        {
          dayName: "Día 4",
          notes: "Actividad libre (Ciclismo, escalada, senderismo, tenis, pádel, baloncesto, natación, etc.)",
          exercises: [],
        },
      ],
    },
    {
      weekNumber: 3,
      title: "Semana 3 (5 días de entrenamiento, se añade balón en 2 días)",
      days: [
        {
          dayName: "Día 1",
          exercises: [
            { name: "Saltos a la comba", repetitions: "2:30 min", rest: "30 seg" },
            { name: "Saltos a la comba", repetitions: "2:30 min", rest: "30 seg" },
            { name: "Sprint 40 m", repetitions: "1", rest: "30 seg" },
            { name: "Flexiones", repetitions: "15", rest: "30 seg" },
            { name: "Sentadillas", repetitions: "20", rest: "30 seg" },
            { name: "Sprint 40 m", repetitions: "1", rest: "30 seg" },
            { name: "Flexiones", repetitions: "15", rest: "30 seg" },
            { name: "Sentadillas", repetitions: "20", rest: "30 seg" },
            { name: "Sprint 40 m", repetitions: "1", rest: "30 seg" },
            { name: "Flexiones", repetitions: "15", rest: "30 seg" },
            { name: "Sentadillas", repetitions: "20", rest: "30 seg" },
            { name: "Sprint 40 m", repetitions: "1", rest: "30 seg" },
            { name: "Saltos verticales", repetitions: "3 x 12", rest: "30 seg" },
            { name: "Ejercicio técnico con balón (Conducción rápida en zigzag + pase contra la pared)", repetitions: "10 min", rest: "-" },
            { name: "Estiramientos", repetitions: "10 min", rest: "-" },
          ],
        },
        { dayName: "Día 2", notes: "Actividad libre", exercises: [] },
        {
          dayName: "Día 3",
          exercises: [
            { name: "Carrera continua", repetitions: "20 min", rest: "5 min" },
            { name: "Skipping alto", repetitions: "30 seg", rest: "30 seg" },
            { name: "Abdominales (elevación de piernas)", repetitions: "15", rest: "30 seg" },
            { name: "Twist ruso", repetitions: "15", rest: "30 seg" },
            { name: "Escaladores", repetitions: "30 seg", rest: "30 seg" },
            { name: "Skipping alto", repetitions: "30 seg", rest: "30 seg" },
            { name: "Abdominales (elevación de piernas)", repetitions: "15", rest: "30 seg" },
            { name: "Twist ruso", repetitions: "15", rest: "30 seg" },
            { name: "Escaladores", repetitions: "30 seg", rest: "30 seg" },
            { name: "Skipping alto", repetitions: "30 seg", rest: "30 seg" },
            { name: "Abdominales (elevación de piernas)", repetitions: "15", rest: "30 seg" },
            { name: "Twist ruso", repetitions: "15", rest: "30 seg" },
            { name: "Escaladores", repetitions: "30 seg", rest: "30 seg" },
            { name: "Estiramientos", repetitions: "10 min", rest: "-" },
          ],
        },
        { dayName: "Día 4", notes: "Actividad libre", exercises: [] },
        {
          dayName: "Día 5",
          exercises: [
            { name: "Saltos a la comba", repetitions: "2:30 min", rest: "30 seg" },
            { name: "Saltos a la comba", repetitions: "2:30 min", rest: "30 seg" },
            { name: "Progresión de menos a más 50 m", repetitions: "2", rest: "30 seg" },
            { name: "Flexiones", repetitions: "10", rest: "30 seg" },
            { name: "Sentadillas", repetitions: "20", rest: "30 seg" },
            { name: "Twist ruso", repetitions: "15", rest: "30 seg" },
            { name: "Progresión de menos a más 50 m", repetitions: "2", rest: "30 seg" },
            { name: "Flexiones", repetitions: "10", rest: "30 seg" },
            { name: "Sentadillas", repetitions: "20", rest: "30 seg" },
            { name: "Twist ruso", repetitions: "15", rest: "30 seg" },
            { name: "Sprint 10 m", repetitions: "3", rest: "30 seg" },
            { name: "Flexiones", repetitions: "10", rest: "30 seg" },
            { name: "Sentadillas", repetitions: "20", rest: "30 seg" },
            { name: "Twist ruso", repetitions: "15", rest: "30 seg" },
            { name: "Ejercicio técnico con balón (Golpes con el interior y empeine contra la pared + control orientado)", repetitions: "10 min", rest: "-" },
            { name: "Estiramientos", repetitions: "10 min", rest: "-" },
          ],
        },
      ],
    },
    {
      weekNumber: 4,
      title: "Semana 4 (6 días de entrenamiento, mayor intensidad y balón en 2 días)",
      days: [
        {
          dayName: "Día 1",
          exercises: [
            { name: "Saltos a la comba", repetitions: "2:30 min", rest: "30 seg" },
            { name: "Sprint 30 m", repetitions: "1", rest: "30 seg" },
            { name: "Flexiones", repetitions: "20", rest: "30 seg" },
            { name: "Sentadillas", repetitions: "25", rest: "30 seg" },
            { name: "Saltos verticales", repetitions: "15", rest: "30 seg" },
            { name: "Sprint 20 m", repetitions: "2", rest: "30 seg" },
            { name: "Flexiones", repetitions: "20", rest: "30 seg" },
            { name: "Sentadillas", repetitions: "25", rest: "30 seg" },
            { name: "Saltos verticales", repetitions: "15", rest: "30 seg" },
            { name: "Sprint 10 m", repetitions: "4", rest: "30 seg" },
            { name: "Flexiones", repetitions: "20", rest: "30 seg" },
            { name: "Sentadillas", repetitions: "25", rest: "30 seg" },
            { name: "Saltos verticales", repetitions: "15", rest: "30 seg" },
            { name: "Ejercicio técnico con balón (Circuito de conducción + pase con control orientado)", repetitions: "10 min", rest: "-" },
            { name: "Estiramientos", repetitions: "10 min", rest: "-" },
          ],
        },
        { dayName: "Día 2", notes: "Actividad libre", exercises: [] },
        {
          dayName: "Día 3",
          exercises: [
            { name: "Carrera continua", repetitions: "30 min", rest: "5 min" },
            { name: "Zancadas", repetitions: "20", rest: "30 seg" },
            { name: "Burpees", repetitions: "20", rest: "30 seg" },
            { name: "Zancadas", repetitions: "20", rest: "30 seg" },
            { name: "Burpees", repetitions: "20", rest: "30 seg" },
            { name: "Zancadas", repetitions: "20", rest: "30 seg" },
            { name: "Burpees", repetitions: "20", rest: "30 seg" },
            { name: "Estiramientos", repetitions: "10 min", rest: "-" },
          ],
        },
        { dayName: "Día 4", notes: "Actividad libre", exercises: [] },
        {
          dayName: "Día 5",
          exercises: [
            { name: "Saltos a la comba", repetitions: "2:30 min", rest: "30 seg" },
            { name: "Sprint 50 m", repetitions: "1", rest: "30 seg" },
            { name: "Flexiones", repetitions: "10", rest: "30 seg" },
            { name: "Abdominales pies suelo", repetitions: "20", rest: "30 seg" },
            { name: "Abdominales oblicuos", repetitions: "25", rest: "30 seg" },
            { name: "Sprint 50 m", repetitions: "1", rest: "30 seg" },
            { name: "Flexiones", repetitions: "10", rest: "30 seg" },
            { name: "Abdominales pies suelo", repetitions: "20", rest: "30 seg" },
            { name: "Abdominales oblicuos", repetitions: "25", rest: "30 seg" },
            { name: "Sprint 50 m", repetitions: "1", rest: "30 seg" },
            { name: "Flexiones", repetitions: "10", rest: "30 seg" },
            { name: "Abdominales pies suelo", repetitions: "20", rest: "30 seg" },
            { name: "Abdominales oblicuos", repetitions: "25", rest: "30 seg" },
            { name: "Sprint 50 m", repetitions: "1", rest: "30 seg" },
            { name: "Ejercicio técnico con balón (hacer toques con el balón (si estáis mas gente \"Que no caiga\") + circuito de zigzag y pase", repetitions: "10 min", rest: "-" },
            { name: "Estiramientos", repetitions: "10 min", rest: "-" },
          ],
        },
        { dayName: "Día 6", notes: "Actividad libre", exercises: [] },
      ],
    },
    {
      weekNumber: 5,
      title: "Semana 5 (Última semana antes de pretemporada, máxima intensidad)",
      days: [
        {
          dayName: "Día 1",
          exercises: [
            { name: "Saltos a la comba", repetitions: "3 min", rest: "30 seg" },
            { name: "Progresión de menos a más 60 m", repetitions: "1", rest: "30 seg" },
            { name: "Flexiones", repetitions: "15", rest: "30 seg" },
            { name: "Sentadillas", repetitions: "30", rest: "30 seg" },
            { name: "Abdominales (elevación de piernas)", repetitions: "20", rest: "30 seg" },
            { name: "Progresión de menos a más 60 m", repetitions: "1", rest: "30 seg" },
            { name: "Flexiones", repetitions: "15", rest: "30 seg" },
            { name: "Sentadillas", repetitions: "30", rest: "30 seg" },
            { name: "Abdominales (elevación de piernas)", repetitions: "20", rest: "30 seg" },
            { name: "Progresión de menos a más 60 m", repetitions: "1", rest: "30 seg" },
            { name: "Flexiones", repetitions: "15", rest: "30 seg" },
            { name: "Sentadillas", repetitions: "30", rest: "30 seg" },
            { name: "Abdominales (elevación de piernas)", repetitions: "20", rest: "30 seg" },
            { name: "Progresión de menos a más 60 m", repetitions: "1", rest: "30 seg" },
            { name: "Ejercicio técnico con balón (Conducción rápida + golpeo a puerta)", repetitions: "10 min", rest: "-" },
            { name: "Estiramientos", repetitions: "10 min", rest: "-" },
          ],
        },
        { dayName: "Día 2", notes: "Actividad libre (Ciclismo, escalada, senderismo, tenis, pádel, baloncesto, natación, etc.)", exercises: [] },
        { dayName: "Día 3", exercises: [{ name: "Carrera continua", repetitions: "35 min", rest: "-" }] },
        { dayName: "Día 4", notes: "Actividad libre (Ciclismo, escalada, senderismo, tenis, pádel, baloncesto, natación, etc.)", exercises: [] },
        {
          dayName: "Día 5",
          exercises: [
            { name: "Saltos a la comba", repetitions: "2:30 min", rest: "30 seg" },
            { name: "Saltos a la comba", repetitions: "2:30 min", rest: "30 seg" },
            { name: "Sprint 70 m", repetitions: "1", rest: "60 seg" },
            { name: "Sprint 70 m", repetitions: "1", rest: "60 seg" },
            { name: "Sprint 70 m", repetitions: "1", rest: "60 seg" },
            { name: "Sprint 70 m", repetitions: "1", rest: "60 seg" },
            { name: "Sprint 70 m", repetitions: "1", rest: "60 seg" },
            { name: "Sprint 70 m", repetitions: "1", rest: "60 seg" },
            { name: "Sprint 70 m", repetitions: "1", rest: "60 seg" },
            { name: "Sprint 70 m", repetitions: "1", rest: "60 seg" },
            { name: "Ejercicio técnico con balón (Conducción, cambios de dirección y sprint corto con balón) Si estáis mas gente podéis hacer Fut-tenis o partido reducido 2vs2, 3vs3, etc.)", repetitions: "10 min", rest: "-" },
          ],
        },
        { dayName: "Día 6", notes: "Descanso activo (paseo, movilidad, estiramientos largos)", exercises: [] },
      ],
    },
  ]
};
